name: "Ollama ROCm"
description: "Get up and running with large language models on AMD graphic cards."
# renovate: datasource=github-tags depName=ollama/ollama
version: "0.17.7-rocm"
slug: "ollama-rocm"
arch:
  - amd64
url: https://ollama.com
map:
  - type: config
    read_only: false
  - type: share
    read_only: false
  - type: addon_config
    read_only: false
    path: /root/.ollama
image: docker.io/ollama/ollama:0.17.7-rocm
init: false
ingress: true
legacy: true
video: true
ingress_port: 11434
ingress_stream: true
ports:
  11434/tcp: 11434
ports_description:
  11434/tcp: "The Ollama API Port, not used for End-User Access"
options:
  OLLAMA_MODELS: /share/ollama
  OLLAMA_KEEP_ALIVE: -1
  OLLAMA_KV_CACHE_TYPE: q8_0
  OLLAMA_FLASH_ATTENTION: 0
  OLLAMA_MAX_LOADED_MODELS: 1
  OLLAMA_NUM_PARALLEL: 1
  OLLAMA_ORIGINS: ""
  OLLAMA_VULKAN: 1
  gpus: all
schema:
  OLLAMA_FLASH_ATTENTION: int
  OLLAMA_MODELS: list(/config/ollama|/share/ollama)
  OLLAMA_KEEP_ALIVE: int
  OLLAMA_KV_CACHE_TYPE: list(f16|q8_0|q4_0)
  OLLAMA_MAX_LOADED_MODELS: int
  OLLAMA_NUM_PARALLEL: int
  OLLAMA_ORIGINS: str
  OLLAMA_API_KEY: str?
  HSA_OVERRIDE_GFX_VERSION: "str?"
  OLLAMA_LLM_LIBRARY: "str?"
  OLLAMA_CONTEXT_LENGTH: "int?"
  OLLAMA_VULKAN: int
  gpus: str
devices:
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
  - /dev/kfd
  - /dev/dri
startup: application
watchdog: tcp://[HOST]:[PORT:11434]
